version: '3.1'

services:
  mysql:
    image: mysql:latest
    command:
      - --binlog-format=ROW
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON
    environment:
      MYSQL_USER: devtam
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: Dev22x22
      MYSQL_DATABASE: do_an
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
volumes:
  mysql-data: